### ISSUE TITLE
Pb avec le compteur Avenue Thouars - Marne

### ISSUE THREAD

**Issue by CyclisteBx** [velo-cite/compteurs-velo#15]
Les moyennes sont calculées:
<img width="413" alt="image" src="https://github.com/velo-cite/compteurs-velo/assets/124528680/368fcb78-5d4d-4324-9bb6-b7bc06d5fbbb">

Mais les records et de les graphiques sont à 0:
<img width="831" alt="image" src="https://github.com/velo-cite/compteurs-velo/assets/124528680/0f60b1b4-8369-4582-bb64-a04602fc9ae7">

**Comment by paulop33** [comment]
Les stats de la métropoles pour la journée d'hier :
https://opendata.bordeaux-metropole.fr/explore/dataset/pc_velo_p/analyze/?disjunctive.ident&refine.ident=Z1705CT1&refine.ident=Z1705CT2&sort=comptage_1h&q.timerange.datedebut=datedebut:%5B2024-02-18T23:00:00Z+TO+2024-02-20T22:59:59Z%5D&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJjb2x1bW4iLCJmdW5jIjoiU1VNIiwieUF4aXMiOiJjb21wdGFnZV8xaCIsInNjaWVudGlmaWNEaXNwbGF5Ijp0cnVlLCJjb2xvciI6IiMwMjY4QTUifV0sInhBeGlzIjoiZGF0ZWZpbiIsIm1heHBvaW50cyI6IiIsInRpbWVzY2FsZSI6ImhvdXIiLCJzb3J0IjoiIiwiY29uZmlnIjp7ImRhdGFzZXQiOiJwY192ZWxvX3AiLCJvcHRpb25zIjp7ImRpc2p1bmN0aXZlLmlkZW50Ijp0cnVlLCJyZWZpbmUuaWRlbnQiOlsiWjE3MDVDVDEiLCJaMTcwNUNUMiJdLCJzb3J0IjoiY29tcHRhZ2VfMWgiLCJxLnRpbWVyYW5nZS5kYXRlZGVidXQiOiJkYXRlZGVidXQ6WzIwMjQtMDItMThUMjM6MDA6MDBaIFRPIDIwMjQtMDItMjBUMjI6NTk6NTlaXSJ9fX1dLCJkaXNwbGF5TGVnZW5kIjp0cnVlLCJhbGlnbk1vbnRoIjp0cnVlLCJ0aW1lc2NhbGUiOiIifQ%3D%3D

On est à 694 au total. Le compteur de la page d'accueil est donc presque bon. (il y a peut-être un décalage d'une heure).
Il faut peut être regarder les identifiants lors du calcul
