### ISSUE TITLE
Site pas mis à jour

### ISSUE THREAD

**Issue by CyclisteBx** [velo-cite/compteurs-velo#17]
Bien que le site ait l'air d'être construit correctement tous les jours, le site affiche actuellement "Page générée le 9 mars"
 
![Untitled](https://github.com/velo-cite/compteurs-velo/assets/124528680/b659bc1e-e733-419c-b1c5-57c27ae7e744)

**Comment by LoicGombeaud** [comment]
Arf, je regarde ça au plus vite (je sais pas quand exactement par contre,
suis un peu charrette en ce moment)

**Comment by LoicGombeaud** [comment]
Je viens de voir que le lien était parti dans la newsletter, je m'en occupe
en urgence dans la matinée

**Comment by LoicGombeaud** [comment]
C'est réparé ! Les cronjobs de "libérons la rue" et "parking" avaient créé une flopée de pods, ce qui fait qu'on avait atteint la limite du nombre de pods sur le cluster. J'ai désactivé les cronjobs pour l'instant et pousserai un fix plus permanent à terme.
