### ISSUE TITLE
Fusion des compteurs sur l'intersection Pompidou x Larminat x Gautier 

### ISSUE THREAD

**Issue by LoicGombeaud** [velo-cite/compteurs-velo#18]
Que diriez-vous de ne montrer qu'un seul compteur « virtuel » à cet endroit, à l'image de ce qui est fait à Martignas ?

En gros, passer de ça :

![image](https://github.com/velo-cite/compteurs-velo/assets/1173317/eaee4247-a8e2-4f66-bc40-7d6f3ed82d1a)

à ça :

![image](https://github.com/velo-cite/compteurs-velo/assets/1173317/a847b58d-e107-46d7-92d5-ae07936d32f6)

**Comment by LoicGombeaud** [comment]
On pourrait imaginer appeler ça « Barrière Saint-Augustin », et d'ailleurs faire pareil à la barrière de Toulouse

![image](https://github.com/velo-cite/compteurs-velo/assets/1173317/041cb993-9bee-4119-a3a6-9e2e52408fc3)

**Comment by paulop33** [comment]
C'est fait ! (par contre, il faudra peut être penser à afficher l'ensemble des capteurs sur la vue détails)
