### ISSUE TITLE
Site ne compile plus

### ISSUE THREAD

**Issue by CyclisteBx** [velo-cite/compteurs-velo#19]
L'opendata a changé pas mal de libélés qui ne sont plus uniques, ca fait planter le site depuis le 29 mai. 

J'ai essayé de modifier le metadata.csv pour prendre en compte les nouveaux libélés mais ca ne suffit pas (les libéles restent non uniques après avoir fait le split sur le mot "vers") je pense qu'on va devoir réflechir à construire les stats sur l'id Z000CT111 qui lui est unique.

**Comment by paulop33** [comment]
Je viens de fix temporairement.
j'ai renommé les Id pour utiliser l'id de la métropole mais pour le moment, on utilise toujours le nom découpé au niveau de vers.. 
Il faudra découper le nom en faisant récupérant la valeur de la zone sans le compteur. Exemple zone de 503 dans Z503CT24.

Par ailleurs la compilation ne fonctionnait pas car la métropole vient d'ajouter un compteur à Villenave d'Ornon (sur le ReVE, coté extérieur de rocade)
